[package]
name = "deoxit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1"
tokio = { version = "1", features = [
    "fs",
    "rt-multi-thread",
    "macros",
    "sync",
] }
